### ISSUE TITLE
Pitanje

### ISSUE THREAD

**Issue by gianthead97** [ivan-ristovic/MATF-Functional-Programming#2]
Zašto ovde:
https://github.com/ivan-ristovic/MATF-Functional-Programming/blob/e898e19f42ba0009e86b59a0f6ac208fc1b339b9/08/04_for_each/main.cpp#L19
kad umesto ove lambde pošaljemo referencu na std::to_string g++ izbaci neku grešku sa potenciranjem nedostajanja operatora().

a ovde: https://github.com/ivan-ristovic/MATF-Functional-Programming/blob/e898e19f42ba0009e86b59a0f6ac208fc1b339b9/08/06_word_count/main.cpp#L35
šaljemo referencu na funkciju najnormalnije

**Comment by ivan-ristovic** [comment]
U prvom slucaju ne moze da prodje zamena sablona ako se samo navede referenca na `std::to_string()` (postoji dosta overload-ova funkcije `std::to_string()` pa nije jasno koji treba pozvati - to se resava tako sto se "da argument" jer je jasno da je `value` zapravo tipa `int`), a u drugom slucaju imamo nasu funkiju koja vraca `std::string` i nema overload-a pa nema dvosmislenosti.

Izvinjavam se na kasnom odgovoru, nisam proveravao GitHub od prekjuce... Nadam se da nije pravilo probleme na ispitu :)
